//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ID_Application { get; set; }
        public string Theme { get; set; }
        public int ID_GuestRoom { get; set; }
        public Nullable<int> ID_DepartStaff { get; set; }
        public int ID_Status { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnding { get; set; }
        public string Remark { get; set; }
    
        public virtual DepartStaff DepartStaff { get; set; }
        public virtual GuestRoom GuestRoom { get; set; }
        public virtual StatusApp StatusApp { get; set; }
    }
}
