//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corpus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Corpus()
        {
            this.Room = new HashSet<Room>();
        }
    
        public int ID_Corpus { get; set; }
        public int ID_Quarter { get; set; }
        public int CorpusNum { get; set; }
        public int ID_StreetCorpus { get; set; }
        public string StreetNum { get; set; }
    
        public virtual Quarter Quarter { get; set; }
        public virtual StreetCorpus StreetCorpus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Room { get; set; }
    }
}
