//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmegaApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppOmegaEntities : DbContext
    {
        public AppOmegaEntities()
            : base("name=AppOmegaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Corpus> Corpus { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DepartStaff> DepartStaff { get; set; }
        public virtual DbSet<Guest> Guest { get; set; }
        public virtual DbSet<GuestRoom> GuestRoom { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Quarter> Quarter { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StatusApp> StatusApp { get; set; }
        public virtual DbSet<StreetCorpus> StreetCorpus { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
